package com.minidb.minidb.tokenizer;

public enum TokenType {
    SELECT, INSERT, UPDATE, DELETE,
    CREATE, DROP, ALTER, SHOW,
    BEGIN, COMMIT, ROLLBACK, TRANSACTION,
    FROM, INTO, VALUES, SET,
    WHERE, AND, OR, ORDER, BY,
    TABLE, TABLES, ADD, COLUMN,
    LIMIT, OFFSET, INDEX, INDEXES, ON,
    JOIN, INNER, DOT,
    COUNT, MAX, MIN, SUM, AVG,
    ASC, DESC, LIKE,
    STAR, EQUALS, NOT_EQUALS, GT, LT, GTE, LTE, COMMA, LPAREN, RPAREN, SEMICOLON,
    PERCENT,
    IDENT, NUMBER, STRING,
    EOF, UNKNOWN
}
